backend: pytorch
tensor_parallel_size: 1
pipeline_parallel_size: 1
max_batch_size: 1280 #768
max_num_tokens: 1280 #2048
max_seq_len: 2048
print_iter_log: false
enable_iter_perf_stats: false
return_perf_metrics: false
enable_layerwise_nvtx_marker: false
stream_interval: 50
enable_chunked_prefill: true
scheduler_config:
  capacity_scheduler_policy: MAX_UTILIZATION
  context_chunking_policy: FIRST_COME_FIRST_SERVED
kv_cache_config:
  dtype: fp8
  free_gpu_memory_fraction: 0.95
  enable_block_reuse: false
num_postprocess_workers: 4
torch_compile_config:
  enable_fullgraph: true
  enable_inductor: false
  enable_piecewise_cuda_graph: true
  enable_userbuffers: true
  capture_num_tokens: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 768, 1024, 1280, 1536, 1792, 2048]
moe_config:
  backend: CUTLASS
cuda_graph_config:
  enable_padding: true
  batch_sizes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 768, 1024, 1280, 1536, 1792, 2048]
cache_transceiver_config:
  backend: DEFAULT
sampler_type: TRTLLMSampler
