{
 "title": "Model runs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "LLAMA2-70B",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "LLAMA2-70B MI325X",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "queryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'llama2-70b' and accelerator == 'mi325x'",
       "rawQueryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'llama2-70b' and accelerator == 'mi325x'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LLAMA2-70B INTERACTIVE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "LLAMA2-70B INTERACTIVE MI325X",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "queryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'llama2-70b-interactive' and accelerator == 'mi325x'",
       "rawQueryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'llama2-70b-interactive' and accelerator == 'mi325x'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "LLAMA3.1-405B",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "LLAMA3.1-405B MI325X",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "queryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rougeL,\n  exact_match,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'llama3_1-405b' and accelerator == 'mi325x'",
       "rawQueryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rougeL,\n  exact_match,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'llama3_1-405b' and accelerator == 'mi325x'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "MIXTRAL-8X7B",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "MIXTRAL-8X7B MI325X",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "queryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  gsm8k,\n  mbxp,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'mixtral-8x7b' and accelerator == 'mi325x'",
       "rawQueryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  gsm8k,\n  mbxp,\n  tokens_per_sample,\n  vllm_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'mixtral-8x7b' and accelerator == 'mi325x'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DEEPSEEK-R1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "DEEPSEEK-R1 MI325X",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "queryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  gsm8k,\n  mbxp,\n  tokens_per_sample,\n  sglang_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'deepseek-r1' and accelerator == 'mi325x'",
       "rawQueryText": "select\n  timestamp as time,\n  run_type,\n  system_name,\n  docker_image,\n  scenario,\n  perf_validity,\n  accuracy_validity,\n  perf_tokens_per_sec,\n  perf_samples_per_sec,\n  perf_target_qps,\n  ttft_lat_99pct_ns,\n  tpot_lat_99pct_ns,\n  rouge1,\n  rouge2,\n  rougeL,\n  gsm8k,\n  mbxp,\n  tokens_per_sample,\n  sglang_commit,\n  harness_commit,\n  hipblaslt_commit,\n  power_settings,\n  artifact_path,\n  notes\nfrom results\nwhere model == 'deepseek-r1' and accelerator == 'mi325x'",
       "timeColumns": [
        "time",
        "ts"
       ]
      }
     ]
    }
   ]
  }
 ]
}