backend: pytorch
max_batch_size: 2048
max_num_tokens: 4096
max_input_len: 2540
max_seq_len: 4096
tensor_parallel_size: 1
pipeline_parallel_size: 1
enable_attention_dp: false
print_iter_log: true
enable_iter_perf_stats: false
cuda_graph_config:
  enable_padding: true
  batch_sizes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
disable_overlap_scheduler: false
kv_cache_config:
  enable_block_reuse: false
  free_gpu_memory_fraction: 0.95
  dtype: fp8
cache_transceiver_config:
  max_tokens_in_buffer: 4096
  backend: UCX
stream_interval: 100
num_postprocess_workers: 4
sampler_type: TRTLLMSampler
scheduler_config:
  capacity_scheduler_policy: MAX_UTILIZATION
  context_chunking_policy: FIRST_COME_FIRST_SERVED
