DYN_LOG: info
HOME: /work
XDG_CACHE_HOME: /work/.cache
VLLM_CACHE_ROOT: /work/.cache/vllm
FLASHINFER_CACHE_DIR: /work/.cache/flashinfer
FLASHINFER_CUBIN_DIR: /work/.cache/flashinfer_cubin/cubins
PYTHONPATH: /work/scaleout/patches
TRITON_CACHE_DIR: /work/.cache/triton
TORCH_EXTENSIONS_DIR: /work/.cache/torch_extensions
NUMBA_CACHE_DIR: /work/.cache/numba
VLLM_LOGGING_LEVEL: INFO
VLLM_USE_FLASHINFER_SAMPLER: 1
VLLM_USE_FLASHINFER_MOE_FP4: 1
VLLM_FLASHINFER_MOE_BACKEND: latency
VLLM_FLASHINFER_WORKSPACE_BUFFER_SIZE: 1610612736
TOKIO_WORKER_THREADS: 16
OMP_NUM_THREADS: 16
VLLM_USE_TRITON_POS_EMBED: 1
