variables:
  DP_MULTIPLICITY:
    type: integer
    value: 64
  GPUS_PER_DP_RANK:
    type: integer
    value: 1
  TOTAL_GPUS:
    type: integer
    value: ${{ variables.DP_MULTIPLICITY * variables.GPUS_PER_DP_RANK }}

  BASE_PORT:
    value: 8336
  MODEL_PATH:
    value: /home/mlperf_inference_storage/models/gpt-oss/gpt-oss-120b
  TRTLLM_YAML:
    value: /work/configs/gpt_oss_120b/Cisco_UCS_B300x64_G200_4x2_RO/TRTLLM/Offline/trtllm-serve-ifb-1gpu.yaml
  TRTLLM_ENV_EXPORTS:
    value: |
      export TLLM_DISABLE_TINYGEMM2='1'
      export TRTLLM_MOE_ENABLE_ALLTOALL_WITHOUT_ALLGATHER='1'
      export TLLM_PROFILE_START_STOP='12000-12100'
      export OMP_NUM_THREADS='4'
      export HF_HOME='/home/mlperf_inference_storage/.cache/huggingface'
      export TRTLLM_WINDOW_SIZE_SHARES='0.05,0.95'
  HTTP_INTERFACE:
    value: ""
  HARNESS_CONFIG_DIR:
    value: /work/configs/gpt_oss_120b/Cisco_UCS_B300x64_G200_4x2_RO/TRTLLM/Offline

  BENCHMARK:
    value: gpt-oss-120b
  SCENARIO:
    value: Offline
  SYSTEM_NAME:
    value: B300-SXM-270GBx64
  TEST_MODE:
    value: PerformanceOnly
  HARNESS_EXTRA_ARGS:
    value: ""
  LOADGEN_MODE:
    value: full
