variables:
  # IFB topology - full GB200x72 scale (18 nodes x 4 GPUs/node = 72 GPUs).
  DP_MULTIPLICITY:
    type: integer
    value: 72
  GPUS_PER_DP_RANK:
    type: integer
    value: 1
  TOTAL_GPUS:
    type: integer
    value: ${{ variables.DP_MULTIPLICITY * variables.GPUS_PER_DP_RANK }}

  BASE_PORT:
    value: 8336

  MODEL_PATH:
    value: /home/mlperf_inference_storage/models/gpt-oss/gpt-oss-120b
  TRTLLM_YAML:
    value: /work/configs/gpt_oss_120b/GB200-NVL72_GB200-186GB_aarch64x72/TRTLLM/Server/trtllm-serve-ifb-1gpu.yaml
  TRTLLM_ENV_YAML:
    value: /work/configs/gpt_oss_120b/GB200-NVL72_GB200-186GB_aarch64x72/TRTLLM/Server/trtllm-serve-ifb-1gpu-env.yaml

  BENCHMARK:
    value: gpt-oss-120b
  SCENARIO:
    value: Server
  SYSTEM_NAME:
    value: GB200-NVL72_GB200-186GB_aarch64x72
  TEST_MODE:
    description: "default performance only mode"
    value: PerformanceOnly
  HARNESS_EXTRA_ARGS:
    value: ""
